-------------------------------------------------------------------------------
-- Noice Neovim Plugin
-------------------------------------------------------------------------------

local colors    = require('mannydark.palette')
local highlight = vim.api.nvim_set_hl
local noice     = {}


--------------------------------------------------------------
-- Settings

noice.setupHighlighting = function()
  ----------------------- Not used by now:
  highlight(0, 'NoiceCmdline',                       { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlineIcon',                   { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlineIconCmdline',            { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlineIconFilter',             { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlineIconHelp',               { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlineIconIncRename',          { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlineIconInput',              { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlineIconLua',                { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlineIconSearch',             { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlinePopup',                  { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlinePopupBorder',            { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlinePopupBorderCmdline',     { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlinePopupBorderFilter',      { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlinePopupBorderHelp',        { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlinePopupBorderIncRename',   { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlinePopupBorderInput',       { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlinePopupBorderLua',         { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlinePopupBorderSearch',      { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCmdlinePrompt',                 { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindClass',       { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindColor',       { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindConstant',    { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindConstructor', { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindDefault',     { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindEnum',        { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindEnumMember ', { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindField',       { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindFile',        { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindFolder',      { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindFunction',    { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindInterface',   { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindKeyword',     { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindMethod',      { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindModule',      { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindProperty',    { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindSnippet',     { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindStruct',      { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindText',        { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindUnit',        { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindValue',       { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemKindVariable',    { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemMenu',            { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCompletionItemWord',            { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceConfirm',                       { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceConfirmBorder',                 { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceCursor',                        { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatConfirm',                 { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatConfirmDefault',          { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatDate',                    { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatEvent',                   { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatKind',                    { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatLevelDebug',              { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatLevelError',              { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatLevelInfo',               { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatLevelOff',                { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatLevelTrace',              { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatLevelWarn',               { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatProgressDone',            { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatProgressTodo',            { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceFormatTitle',                   { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceLspProgressClient',             { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceLspProgressSpinner',            { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceLspProgressTitle',              { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceMini',                          { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoicePopup',                         { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoicePopupBorder',                   { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoicePopupmenu',                     { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoicePopupmenuBorder',               { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoicePopupmenuMatch',                { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoicePopupmenuSelected',             { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceScrollbar',                     { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceScrollbarThumb',                { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceSplit',                         { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceSplitBorder',                   { fg = colors.blue, bg = colors.purple })
  highlight(0, 'NoiceVirtualText',                   { fg = colors.blue, bg = colors.purple })
end

return noice

