local theme = {}

theme.buildTheme = function()
  -- Editor:
  require("mannydark.highlighting.editor.buffer"             ).setupHighlighting()
  require("mannydark.highlighting.editor.environment"        ).setupHighlighting()
  require("mannydark.highlighting.editor.statusline"         ).setupHighlighting()

  -- Language Defaults (MUST load first - provides base for all languages):
  require("mannydark.highlighting.languages.languagedefaults").setupHighlighting()

  -- Core Languages (commonly used):
  require("mannydark.highlighting.languages.ada"             ).setupHighlighting()
  require("mannydark.highlighting.languages.bash"            ).setupHighlighting()
  require("mannydark.highlighting.languages.brainfuck"       ).setup()  -- Includes filetype + syntax
  require("mannydark.highlighting.languages.c"               ).setupHighlighting()
  require("mannydark.highlighting.languages.csharp"          ).setupHighlighting()
  require("mannydark.highlighting.languages.css"             ).setupHighlighting()
  require("mannydark.highlighting.languages.html"            ).setupHighlighting()
  require("mannydark.highlighting.languages.javascript"      ).setupHighlighting()
  require("mannydark.highlighting.languages.json"            ).setupHighlighting()
  require("mannydark.highlighting.languages.lua"             ).setupHighlighting()
  require("mannydark.highlighting.languages.markdown"        ).setupHighlighting()
  require("mannydark.highlighting.languages.php"             ).setupHighlighting()
  require("mannydark.highlighting.languages.scss"            ).setupHighlighting()
  require("mannydark.highlighting.languages.shell"           ).setupHighlighting()
  require("mannydark.highlighting.languages.toml"            ).setupHighlighting()
  require("mannydark.highlighting.languages.typescript"      ).setupHighlighting()
  require("mannydark.highlighting.languages.vimscript"       ).setupHighlighting()
  require("mannydark.highlighting.languages.xml"             ).setupHighlighting()
  require("mannydark.highlighting.languages.yml"             ).setupHighlighting()
  require("mannydark.highlighting.languages.zsh"             ).setupHighlighting()

  -- Uncomment languages as needed (commented out to avoid E849: Too many highlight groups):
  -- require("mannydark.highlighting.languages.awk"           ).setupHighlighting()
  -- require("mannydark.highlighting.languages.assembly"      ).setupHighlighting()
  -- require("mannydark.highlighting.languages.batch"         ).setupHighlighting()
  -- require("mannydark.highlighting.languages.clojure"       ).setupHighlighting()
  -- require("mannydark.highlighting.languages.cobol"         ).setupHighlighting()
  -- require("mannydark.highlighting.languages.coffeescript"  ).setupHighlighting()
  -- require("mannydark.highlighting.languages.cpp"           ).setupHighlighting()
  -- require("mannydark.highlighting.languages.cypher"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.d"             ).setupHighlighting()
  -- require("mannydark.highlighting.languages.dart"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.dhall"         ).setupHighlighting()
  -- require("mannydark.highlighting.languages.dockercompose" ).setupHighlighting()
  -- require("mannydark.highlighting.languages.elixir"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.erlang"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.elm"           ).setupHighlighting()
  -- require("mannydark.highlighting.languages.fish"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.fortran"       ).setupHighlighting()
  -- require("mannydark.highlighting.languages.fsharp"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.go"            ).setupHighlighting()
  -- require("mannydark.highlighting.languages.graphql"       ).setupHighlighting()
  -- require("mannydark.highlighting.languages.groovy"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.hack"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.haskell"       ).setupHighlighting()
  -- require("mannydark.highlighting.languages.hcl"           ).setupHighlighting()
  -- require("mannydark.highlighting.languages.inifiles"      ).setupHighlighting()
  -- require("mannydark.highlighting.languages.java"          ).setupHighlighting()
  require("mannydark.highlighting.languages.jsonnet"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.julia"         ).setupHighlighting()
  -- require("mannydark.highlighting.languages.kotlin"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.labview"       ).setupHighlighting()
  -- require("mannydark.highlighting.languages.lisp"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.logo"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.malbolge"      ).setupHighlighting()
  -- require("mannydark.highlighting.languages.matlab"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.nim"           ).setupHighlighting()
  -- require("mannydark.highlighting.languages.nix"           ).setupHighlighting()
  -- require("mannydark.highlighting.languages.objc"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.ocaml"         ).setupHighlighting()
  -- require("mannydark.highlighting.languages.pascal"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.perl"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.plsql"         ).setupHighlighting()
  -- require("mannydark.highlighting.languages.powershell"    ).setupHighlighting()
  -- require("mannydark.highlighting.languages.pulumi"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.python"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.purescript"    ).setupHighlighting()
  -- require("mannydark.highlighting.languages.racket"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.r"             ).setupHighlighting()
  -- require("mannydark.highlighting.languages.rescript"      ).setupHighlighting()
  -- require("mannydark.highlighting.languages.rust"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.ruby"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.sas"           ).setupHighlighting()
  -- require("mannydark.highlighting.languages.scala"         ).setupHighlighting()
  -- require("mannydark.highlighting.languages.scratch"       ).setupHighlighting()
  -- require("mannydark.highlighting.languages.scheme"        ).setupHighlighting()
  -- require("mannydark.highlighting.languages.sml"           ).setupHighlighting()
  -- require("mannydark.highlighting.languages.sql"           ).setupHighlighting()
  -- require("mannydark.highlighting.languages.starlark"      ).setupHighlighting()
  -- require("mannydark.highlighting.languages.swift"         ).setupHighlighting()
  -- require("mannydark.highlighting.languages.tcl"           ).setupHighlighting()
  -- require("mannydark.highlighting.languages.tsql"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.vbnet"         ).setupHighlighting()
  -- require("mannydark.highlighting.languages.verilog"       ).setupHighlighting()
  -- require("mannydark.highlighting.languages.vhdl"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.wasm"          ).setupHighlighting()
  -- require("mannydark.highlighting.languages.whitespace"    ).setupHighlighting()
  -- require("mannydark.highlighting.languages.zig"           ).setupHighlighting()

  -- Frameworks:
  require("mannydark.highlighting.frameworks.laravelblade"   ).setupHighlighting()
  require("mannydark.highlighting.frameworks.react"          ).setupHighlighting()

  -- Plugins:
  require("mannydark.highlighting.plugins.aerial"            ).setupHighlighting()
  require("mannydark.highlighting.plugins.dap"               ).setupHighlighting()
  require("mannydark.highlighting.plugins.copilot"           ).setupHighlighting()
  require("mannydark.highlighting.plugins.diffview"          ).setupHighlighting()
  require("mannydark.highlighting.plugins.flash"             ).setupHighlighting()
  require("mannydark.highlighting.plugins.fugitive"          ).setupHighlighting()
  require("mannydark.highlighting.plugins.gitsigns"          ).setupHighlighting()
  require("mannydark.highlighting.plugins.hop"               ).setupHighlighting()
  require("mannydark.highlighting.plugins.indent_blankline" ).setupHighlighting()
  require("mannydark.highlighting.plugins.lazy"              ).setupHighlighting()
  require("mannydark.highlighting.plugins.lsp"               ).setupHighlighting()
  require("mannydark.highlighting.plugins.lualine"           ).setupHighlighting()
  require("mannydark.highlighting.plugins.mason"             ).setupHighlighting()
  require("mannydark.highlighting.plugins.mini"              ).setupHighlighting()
  require("mannydark.highlighting.plugins.navic"             ).setupHighlighting()
  require("mannydark.highlighting.plugins.neogit"            ).setupHighlighting()
  require("mannydark.highlighting.plugins.neotest"           ).setupHighlighting()
  require("mannydark.highlighting.plugins.neotree"           ).setupHighlighting()
  require("mannydark.highlighting.plugins.noice"             ).setupHighlighting()
  require("mannydark.highlighting.plugins.notify"            ).setupHighlighting()
  require("mannydark.highlighting.plugins.nvimcmp"           ).setupHighlighting()
  require("mannydark.highlighting.plugins.nvimtree"          ).setupHighlighting()
  require("mannydark.highlighting.plugins.packer"            ).setupHighlighting()
  require("mannydark.highlighting.plugins.telescope"         ).setupHighlighting()
  require("mannydark.highlighting.plugins.todocomments"      ).setupHighlighting()
  require("mannydark.highlighting.plugins.trouble"           ).setupHighlighting()
  require("mannydark.highlighting.plugins.whichkey"          ).setupHighlighting()

  -- Todo:
  require("mannydark.highlighting.todos"                     ).setupHighlighting()
end

return theme
